schema_version = 3

[project]
uuid = "f0e26664-5088-4c32-9b25-26c6bc43bf3e"
name = "numeralform"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"
