[compat.num2words]
repository = "savoirfairelinux/num2words"
commit = "07814cb114157f582c40a00119c2e9faba8dcee2"
version = "0.5.14"
locales = [
  "am", "ar", "az", "be", "bn", "ca", "ce", "cs", "cy", "da", "de", "en",
  "en-IN", "en-NG", "eo", "es", "es-CO", "es-CR", "es-GT", "es-NI", "es-VE",
  "fa", "fi", "fr", "fr-BE", "fr-CH", "fr-DZ", "he", "hi", "hu", "hy", "id",
  "is", "it", "ja", "kn", "ko", "kz", "lt", "lv", "mn", "nl", "no", "pl",
  "pt", "pt-BR", "ro", "ru", "sk", "sl", "sr", "sv", "te", "tet", "tg",
  "th", "tr", "uk", "vi", "zh", "zh-CN", "zh-HK", "zh-TW"
]
forms = ["cardinal", "ordinal", "ordinal_num", "year", "currency"]
profiles = ["integer", "decimal", "string", "currency", "errors"]
values = [0, 1, 2, 3, 10, 11, 19, 20, 21, 42, 99, 100, 101, 999, 1000, 2024]
